# Generated by Django 5.1.5 on 2025-06-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="marksclass",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="marksclass",
            name="assign",
        ),
        migrations.AlterModelOptions(
            name="studentcourse",
            options={},
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(default="2025-03-01"),
        ),
        migrations.AlterField(
            model_name="student",
            name="DOB",
            field=models.DateField(default="2003-01-01"),
        ),
        migrations.DeleteModel(
            name="Marks",
        ),
        migrations.DeleteModel(
            name="MarksClass",
        ),
    ]
